### ISSUE TITLE
xERM-TDE ImageNet Performance

### ISSUE THREAD

**Issue by zuglerQ** [BeierZhu/xERM#1]
Dear Beier, 
Thank you for your innovative work and I am really interested in it. However, when training the ImageNet_LT dataset with xERM-TDE method, I got low performance only 14.4 in the overall accuracy. I would like to ask, is it convenient to share the ImageNet_LT training code or configs there to make sure we could get your sota results?

**Comment by BeierZhu** [comment]
Hello, the training code for ImageNet_LT on xERM-TDE will be updated after ECCV deadline.

**Comment by zuglerQ** [comment]
Thank you for your reply. I am looking forward to the updated code.

**Comment by BeierZhu** [comment]
https://drive.google.com/file/d/1SZ9g-03Jn31o-iFySTHb_Z8dSRxEsV8G/view?usp=sharing

Hi, I don't have time to clean up the code and write readme for the rest datasets and backbones. I just zip all the code for xERM-TDE. You  can refer to the xERM-PC to reproduce the results of xERM-TDE.
