### ISSUE TITLE
how  to  get a balanced model

### ISSUE THREAD

**Issue by asd123-1** [BeierZhu/xERM#3]
Dear Beier:
      I'm very interested in your work！In your code，I can  get a  imbalanced model by TDE, but I don't how do you get the balanced model ?

**Comment by asd123-1** [comment]
I'm sorry I made a mistake. I understand that TDE is a balanced model

**Comment by asd123-1** [comment]
I read your code carefully again, corresponding to your paper, and understood your code， TDE is a balanced model, TE is  an imbalanced model.  Is  that right?

**Comment by BeierZhu** [comment]
You are correct. Similarly, CE is an imbalanced model and CE with Post-Compensate is a balanced model.
